### ISSUE TITLE
Bug after cancel

### ISSUE THREAD

**Issue by Tobi7889** [Lacrimosa99/Easy-WI-ARK-Mod-Manager#18]
Hello,

i have tried to install mods, i failed and pushed "CTRL + C" on console.

**Now it show:**
```
Checking for the latest installer and updater Script
You are using the up to date manager version 2.5.6

Updater is currently running... please try again later.

Thanks for using this script and have a nice Day.
```

I have re-created the script and re-started the server, but the issue is still exist.

**Comment by Tobi7889** [comment]
**fixed** 
I have deleted files in "/tmp" folder.

Maybe, you can add a function for deleting?

**Comment by Lacrimosa99** [comment]
"CTRL + C" to abort is not the best way...
I have a security feature implement to suppress a second process.
please dont abort the update process...
