### ISSUE TITLE
Allow separation of Gamemaster and WebInterface

### ISSUE THREAD

**Issue by Nurtic-Vibe** [Lacrimosa99/Easy-WI-ARK-Mod-Manager#24]
Currently the Database connection is hardcoded, so the script only works when GameMaster and WebInterface are on the same machine

**Comment by Lacrimosa99** [comment]
No, he can connect a remote connection to another server. I have write a remote ip question into the string.

Line 759 in the currently Script.

**Comment by Lacrimosa99** [comment]
check if Database IP = localhost or extern IP.
mysql -h <- for remote IP

**Comment by Lacrimosa99** [comment]
https://github.com/Lacrimosa99/Easy-WI-ARK-Mod-Manager/commit/2ad499cb6e9273499a0299094496ae307b86b396

**Comment by Nurtic-Vibe** [comment]
Please also add a check if DATABASE_HOST etc. are already set and don't ask / ask only once if true.

**Comment by Lacrimosa99** [comment]
Line 893 + 866 makes that ;)
