### ISSUE TITLE
STRG + C löscht TEMP Datei nicht

### ISSUE THREAD

**Issue by xRaid96** [Lacrimosa99/Easy-WI-ARK-Mod-Manager#36]
Wenn man in dem Script STRG + C zum canceln drückt, wird die temp Datei im easy-wi Ordner leider nicht gelöscht und das Script meckert rum, dass es bereits laufen würde.

**Comment by Lacrimosa99** [comment]
https://github.com/Lacrimosa99/Easy-WI-ARK-Mod-Manager/issues/18
