### ISSUE TITLE
Mods, die eine ID haben, die weniger als 10 Zeichen haben, können nicht installiert werden

### ISSUE THREAD

**Issue by xRaid96** [Lacrimosa99/Easy-WI-ARK-Mod-Manager#37]
In der INSTALL() Funktion wird vorausgesetzt, dass die Mod ID 10 Zeichen lang ist. Es gibt aber durchaus auch Mods, die eine ID haben, die nur 9 Zeichen lang ist. Bsp. hier: http://steamcommunity.com/sharedfiles/filedetails/?id=972887420

Wenn ich diesen Mod installieren will, bekomme ich einen invalid input error.

**Comment by Lacrimosa99** [comment]
Der Code berücksichtigt bis zu 10 Zeichen.
Sprich... die ID darf bis _zu_ 10 Zeichen lang sein.

**Comment by xRaid96** [comment]
Komischerweise wollte er die mods nicht updaten, die nur 9 Zeichen lang
waren. Habe ich diese Zahl 10 in der INSTALL Funktion auf 9 geändert, hatte
ich keine probleme mehr. Und zum Thema Strg+c. Wenn das Script mir dauernd
Invalid Input sagt, dann habe ich gar keine andere Möglichkeit als das
Script so zu beenden

**Comment by Lacrimosa99** [comment]
STRG + C: Da die Fehlermeldung als Loop geschrieben ist, sollte diese mit diesem Patch behoben sein: https://github.com/Lacrimosa99/Easy-WI-ARK-Mod-Manager/issues/26

Mit denn 9 Zeichen teste ich nochmal aber bin mir sicher, dass es beim Test keine Fehler gab.

**Comment by Lacrimosa99** [comment]
Confirmed... wird noch behoben.
