### ISSUE TITLE
Script fragt mich beim installieren von neuen Mods immer wieder nach den ext. Database Settings.

### ISSUE THREAD

**Issue by xRaid96** [Lacrimosa99/Easy-WI-ARK-Mod-Manager#38]
Die ext. Database Settings sind ja in der /root/ark_mod_updater_db.conf gespeichert. Wäre es möglich, dass das Script beim installieren eines Mods die Daten aus dieser Datei ausliest und dann anwendet? Das Script könnte ja ggf eine Abfrage an den User machen, ob diese Daten noch korrekt sind oder soetwas.

**Comment by Lacrimosa99** [comment]
Das Script fragt nur 1x ab ob die DB Verbindung stimmt... sollte es beim 2.ten Login zu fehlern kommen, kommt die Meldung erneut.

**Comment by xRaid96** [comment]
Datei mit den Daten ist vorhanden:
https://i.imgur.com/Rj4eHh2.png

Daten stimmen logischerweise auch

**Comment by Lacrimosa99** [comment]
Werd es mir mal anschauen und ggf. berichtigen.

**Comment by Lacrimosa99** [comment]
Kannst es nun mal testen... hab nen Check eingebaut der prüft, ob die File existiert und liesst aus dieser die nötigen Daten aus.
