### ISSUE TITLE
Mods können nicht geupdatet werden

### ISSUE THREAD

**Issue by ehylla93** [Lacrimosa99/Easy-WI-ARK-Mod-Manager#41]
Hallo,

seit einigen Tagen funktioniert das Update der Mods nicht mehr

1  -  Install a certain ModID
2  -  Install all ModIDs
3  -  Install Updater Script and Cronjob

5  -  Update all installed ModIDs

7  -  Uninstall a certain ModID
8  -  Uninstall all ModIDs
9  -  Uninstall Updater Script

0  -  EXIT

Number:  1

Please enter your ModID and press Return: 1122524327

ARK Mod ID:   1122524327
ARK Mod Name:

Are these details correct? [Y/N]?: y

Steam Community is currently not available or ModID 1122524327 unknown!
Please try again later.

Do you want to install additional ModIDs [Y/N]?: n

**Comment by Lacrimosa99** [comment]
Die Mod, welche du Updaten möchtest, wird nicht mehr weiter entwickelt.
https://steamcommunity.com/sharedfiles/filedetails/?id=1122524327
Das Script prüft auf weiter Entwicklung oder ob diese eingestellt wurde und gibt es dementsprechend in der Logfile aus.
Nicht mehr weiter Entwickelte Mods werden nicht geupdatet, da sich die Version nicht ändert und unnötig Traffic erzeugt.
Gruß

**Comment by ehylla93** [comment]
Daran habe ich auch schon gedacht, aber was hat dann folgendes zu bedeuten:

1  -  Install a certain ModID
2  -  Install all ModIDs
3  -  Install Updater Script and Cronjob

5  -  Update all installed ModIDs

7  -  Uninstall a certain ModID
8  -  Uninstall all ModIDs
9  -  Uninstall Updater Script

0  -  EXIT


Number:  5


Steam Community is currently not available or ModID 730794403 unknown!
Please try again later.
Steam Community is currently not available or ModID 1148802682 unknown!
Please try again later.
Steam Community is currently not available or ModID 1146018267 unknown!
Please try again later.
Steam Community is currently not available or ModID 1130324993 unknown!
Please try again later.
Steam Community is currently not available or ModID 1167313300 unknown!
Please try again later.
Steam Community is currently not available or ModID 510590313 unknown!
Please try again later.
Steam Community is currently not available or ModID 558651608 unknown!
Please try again later.
Steam Community is currently not available or ModID 564895376 unknown!
Please try again later.
Steam Community is currently not available or ModID 708807240 unknown!
Please try again later.
Steam Community is currently not available or ModID 711047840 unknown!
Please try again later.
Steam Community is currently not available or ModID 751991809 unknown!
Please try again later.
Steam Community is currently not available or ModID 815252862 unknown!
Please try again later.
Steam Community is currently not available or ModID 815306540 unknown!
Please try again later.
Steam Community is currently not available or ModID 814125806 unknown!
Please try again later.
Steam Community is currently not available or ModID 869153615 unknown!
Please try again later.
Steam Community is currently not available or ModID 880871931 unknown!
Please try again later.
Steam Community is currently not available or ModID 880887081 unknown!
Please try again later.
Steam Community is currently not available or ModID 880947262 unknown!
Please try again later.
Steam Community is currently not available or ModID 922859221 unknown!
Please try again later.
Steam Community is currently not available or ModID 924933745 unknown!
Please try again later.
Steam Community is currently not available or ModID 942185438 unknown!
Please try again later.
Steam Community is currently not available or ModID 506506101 unknown!
Please try again later.
Steam Community is currently not available or ModID 693416678 unknown!
Please try again later.
Steam Community is currently not available or ModID 731604991 unknown!
Please try again later.
Steam Community is currently not available or ModID 928102085 unknown!
Please try again later.
Steam Community is currently not available or ModID 916788716 unknown!
Please try again later.
Steam Community is currently not available or ModID 1122524327 unknown!
Please try again later.

**Comment by Lacrimosa99** [comment]
Scheinbar ist die Community Server nicht erreichbar gewesen in der Zeit... wurde es heut Abend nochmal getestet?
Firewall wurde für den Download freigegeben?

**Comment by ehylla93** [comment]
Ja, habe ich gerade jetzt noch einmal getestet. Es hatte soweit auch ohne Probleme funktioniert, nur jetzt nicht mehr. Entsprechende Einträge sind in der Firewall auch freigegeben.

**Comment by Lacrimosa99** [comment]
Bitte mal Debugger einschalten und die Ausgabe mitteilen.

*Edit*
Hab möglicherweise den Fehler gefunden... bitte den Manager per Hand Updaten!

**Comment by ehylla93** [comment]
Danke, mit dem letzten Update funktioniert es wieder!
