### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by DiTechRacer** [Lacrimosa99/Easy-WI-ARK-Mod-Manager#8]
Hey,

wie siehts mit einer detailierten Installationsanleitung auf deutsch aus?

**Comment by Lacrimosa99** [comment]
Englisch wird vorausgesetzt.
Updatet und Manager ins Root Verzeichniss, 700 (only Root kann lesen, schreiben und ausführen) und den Manager per console ausführen.
Den updater in die crontab schreiben und jede Stunde prüfen lassen.
Download wird als User ausgeführt... Das Script selbst als super User. 
Gruss

**Comment by DiTechRacer** [comment]
Vielen Dank!
