### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by ino89** [Lacrimosa99/Easy-WI-ARK-Mod-Manager#9]
Hallo,

Könnten sie mir erklären wie ich das genau installiert bekommen.
Und wie ich genau vor gehn muss damit die addons im Webinterface erscheinen?

Mfg
Ino

**Comment by Lacrimosa99** [comment]
Eine kleine Anleitung findest du hier: https://github.com/Lacrimosa99/Easy-WI-ARK-Mod-Manager/issues/8

Wie du die Addons ins WI bekommst, geht wie folgt:

Sobald du ein Addon über den Manager gedownloaded hast, erscheint im Homeverzeichnis des Masterservers ein Ordner Namens "easywi-xml-files".
Darin befinden sich alle XML Files für das WI, welche du über die Import Funktion des WI´s importieren kannst.
Einige Anpassungen des Mod Namens sind noch nötig, da nicht bei allen Mods die Versionsnummer gelöscht wird ("Mod-XY-2.0").

Gruß

**Comment by ino89** [comment]
Danke für die schnelle antwort!

Jetzt habe ich aber das Problem das der mein Masteruser nicht erkennen will.

Habe dann mal den Debug Modus angemacht aber der Mach mich nicht schlauer!
Eventuell sagt er dir etwas
- id
- grep 'uid=0('
- '[' 0 '!=' 0 ']'
- USERCHECK
- echo
- echo
- '[' -d /home/easy-wi/masteraddons ']'
- '[' '!' easy-wi = '' ']'
  ++ cat /etc/passwd
  ++ grep easy-wi
  ++ cut -c 27-
- USER_CHECK=/easy-wi:/bin/bash
- '[' '!' /easy-wi:/bin/bash == /home/easy-wi:/bin/bash ']'
- '[' '!' /easy-wi:/bin/bash == /home/easy-wi/:/bin/bash ']'
- redMessage 'User easy-wi not found!'
- echo -e '\033[31;1mUser easy-wi not found!\033[0m'
  User easy-wi not found!
- redMessage 'Please check the Masteruser in this Script.'
- echo -e '\033[31;1mPlease check the Masteruser in this Script.\033[0m'
  Please check the Masteruser in this Script.
- FINISHED
- CLEANFILES
- rm -rf /home/easy-wi/masterserver/steamCMD/steamapps/workshop/content/346110
- rm -rf /home/easy-wi/masterserver/steamCMD/steamapps/workshop/downloads/346110
- '[' -f /home/easy-wi/temp/ark_custom_appid_tmp.log ']'
- '[' '!' '' = INSTALLALL ']'
- rm -rf '/home/easy-wi/masterserver/steamCMD/steamapps/workshop/downloads/state_346110_*'
- rm -rf /home/easy-wi/masterserver/steamCMD/steamapps/workshop/appworkshop_346110.acf
- '[' -f /home/easy-wi/temp/ark_spinner ']'
- echo
- echo
- tput cnorm
- '[' ON == ON ']'
- set +x
  Thanks for using this script and have a nice Day.

###################################################

#### EASY-WI - www.Easy-WI.com

#### ARK - Mod / Content Manager

#### Version: 2.1

#### by

#### Lacrimosa99

#### www.Devil-Hunter-Clan.de

#### www.Devil-Hunter-Multigaming.de

###################################################

Gruß

**Comment by Lacrimosa99** [comment]
Der User ist der falsche... bitte prüfe mit einem "ls -la /home" ob der User und deren Ordner auch existiert.
Das Script prüft ob der User vorhanden ist und ob in seinem Homeverzeichniss auch der Ordner "Masteraddons" existiert.
Bei weiteren Fragen bin ich ab 21 Uhr im TS bei mir (ts.devil-hunter-multigaming.de).

Gruß

**Comment by ino89** [comment]
Der User existiert..

drwxr-x--- 11 easy-wi easy-wi 4096 Sep 19 18:34 easy-wi

und der Ordner ist auch vorhanden.. aber klein geschrieben das dürfte ja kein problem sein.

Wie lange bist den ca da ? da ich Spätdienst haben und erst gegen 23 uhr zuhause bin.

Gruß

**Comment by Lacrimosa99** [comment]
hab aktuell noch 30 min... wenn de dich beeilst.. können wir das gleich machen ;)

**Comment by ino89** [comment]
bin im ts ;)

**Comment by Lacrimosa99** [comment]
Fehler gefunden und behoben.

Fix: https://github.com/Lacrimosa99/Easy-WI-ARK-Mod-Manager/commit/4c048310b29b3a80bf9a083df3b3cec081376052
